igbo_dictionary = {
    "hello": "ndeewo",
    "welcome": "nnọọ",
    "please": "biko",
    "thank you": "daalụ",
    "sorry": "ndo",
    "yes": "e",
    "no": "mba",
    "good morning": "ụtụtụ ọma",
    "good night": "ka chifoo",
    "how are you?": "kedu?",
    "person": "mmadụ",
    "man": "nwoke",
    "woman": "nwanyị",
    "child": "nwa",
    "father": "nna",
    "mother": "nne",
    "friend": "enyi",
    "king": "eze",
    "god": "chukwu",
    "family": "ezi na ụlọ",
    "come": "bịa",
    "go": "gaa",
    "eat": "rie",
    "drink": "ñụọ",
    "sleep": "rahu",
    "wake up": "teta",
    "run": "gbaa ọsọ",
    "walk": "ije",
    "sit": "nọdụ",
    "stand": "kwụrụ",
    "look": "lee",
    "see": "hụ",
    "speak": "kwuo",
    "listen": "ge ntị",
    "work": "rụọ ọrụ",
    "play": "gwuo egwu",
    "laugh": "chị ọchị",
    "cry": "bee akwa",
    "love": "hụ n'anya",
    "buy": "zụọ",
    "sell": "ree",
    "water": "mmiri",
    "fire": "ọkụ",
    "sun": "anwụ",
    "moon": "ọnwa",
    "rain": "mmiri ozuzo",
    "wind": "ikuku",
    "land/ground": "ala",
    "sky": "elu igwe",
    "tree": "osisi",
    "road": "ụzọ",
    "food": "nri",
    "meat": "anụ",
    "fish": "azụ",
    "yam": "ji",
    "pepper": "ose",
    "salt": "nnu",
    "oil": "mmanụ",
    "house": "ụlọ",
    "car": "ụgbọ ala",
    "money": "ego",
    "book": "akwụkwọ",
    "door": "ụzọ / ọnụ ụzọ",
    "chair": "oche",
    "bag": "akpa",
    "knife": "mma",
    "head": "isi",
    "eye": "anya",
    "nose": "imi",
    "mouth": "ọnụ",
    "ear": "ntị",
    "hand": "aka",
    "leg": "ụkwụ",
    "stomach": "afọ",
    "heart": "obi",
    "blood": "ọbara",
    "one": "otu",
    "two": "abụọ",
    "three": "atọ",
    "four": "anọ",
    "five": "ise",
    "six": "isii",
    "seven": "asaa",
    "eight": "asatọ",
    "nine": "itoolu",
    "ten": "iri",
    "big": "ukwu",
    "small": "obere",
    "good": "ọma",
    "bad": "ọjọọ",
    "beautiful": "mara mma",
    "hot": "ọkụ",
    "cold": "oyi",
    "white": "ọcha",
    "black": "oji",
    "red": "uhie",
    "time": "oge",
    "today": "taata",
    "tomorrow": "echi",
    "yesterday": "nnyahụ",
    "life": "ndụ",
    "death": "ọnwụ",
    "market": "ahịa",
    "school": "ụlọ akwụkwọ",
    "church": "ụlọ ụka",
    "name": "aha"
}
print("welcome to kingsley python dictionary and here i can transcribe 100 english words to igbo")
def loop():
    choice = input("write down your choice of word here ==> ")
    print(igbo_dictionary[choice.lower()])
    loop()

loop()